// File generated by FlutterFire CLI. PLACEHOLDER — reemplazar antes de release.
//
// Para generar el archivo real:
//   1. dart pub global activate flutterfire_cli
//   2. flutterfire configure --project=<tu-project-id-firebase>
//
// Ese comando sobreescribe este archivo y además coloca GoogleService-Info.plist
// en ios/Runner/ (agregarlo al target Runner en Xcode manualmente).
//
// Mientras tanto, la app arranca pero las notificaciones push NO funcionan
// (init() en push_service.dart se salta si Firebase no puede configurarse).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions no está configurado para web. '
        'Ejecutá `flutterfire configure` para generar este archivo.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions no soporta esta plataforma. '
          'Ejecutá `flutterfire configure`.',
        );
    }
  }

  // TODO: reemplazar con los valores reales del proyecto Firebase.
  // Estos valores SON PLACEHOLDERS y van a hacer que init() falle ruidosamente.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PLACEHOLDER_IOS_API_KEY',
    appId: 'PLACEHOLDER_IOS_APP_ID',
    messagingSenderId: 'PLACEHOLDER_SENDER_ID',
    projectId: 'PLACEHOLDER_PROJECT_ID',
    storageBucket: 'PLACEHOLDER_PROJECT_ID.appspot.com',
    iosBundleId: 'com.monacobarber.monacoMobile',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PLACEHOLDER_ANDROID_API_KEY',
    appId: 'PLACEHOLDER_ANDROID_APP_ID',
    messagingSenderId: 'PLACEHOLDER_SENDER_ID',
    projectId: 'PLACEHOLDER_PROJECT_ID',
    storageBucket: 'PLACEHOLDER_PROJECT_ID.appspot.com',
  );
}
